spring:
  application:
    name: BirBuket
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml


  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: arxideya464
    username: birbuket
    driver-class-name: org.postgresql.Driver


  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: true
  springdoc:
    api-docs:
      enabled: true
    swagger-ui:
      enabled: true

